'\" t
.\"     Title: 
    nextword
  
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 12/19/2013
.\"    Manual: 
.\"    Source: 
.\"  Language: English
.\"
.TH "NEXTWORD" "1" "12/19/2013" ""
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"

    nextword
   \- display next predicted words (in reverse order)
.SH "SYNOPSIS"
.HP \w'\fBnextword\fR\ 'u
\fBnextword\fR [\-t] [\-r] [\-s\ \fIspname\fR] [\-v] {prefix}
.SH "DESCRIPTION"
.PP
Given a partial (part of) sentence from the end, it outputs the next words allowed in the specified grammar\&.
.PP

\&.dfa,
\&.dict
and
\&.term
files are needed to execute\&. They can be generated from
\&.grammar
and
\&.voca
file by
\fBmkdfa\&.pl\fR\&.
.PP
Please note that the latter part of sentence should be given, since the main 2nd pass does a right\-to\-left parsing\&.
.SH "OPTIONS"
.PP
\fB \-t \fR
.RS 4
Input / Output in category name\&. (default: word)
.RE
.PP
\fB \-r \fR
.RS 4
Enter in reverse order
.RE
.PP
\fB \-s \fR \fIspname\fR
.RS 4
the name string of short\-pause word to be supressed (default: "sp")
.RE
.PP
\fB \-v \fR
.RS 4
Debug output\&.
.RE
.SH "EXAMPLES"
.PP
Exmple output of a sample grammar "fruit":
.sp
.if n \{\
.RS 4
.\}
.nf
% \fBnextword\fR fruit
Stat: init_voca: read 36 words
Reading in term file (optional)\&.\&.\&.done
15 categories, 36 words
DFA has 26 nodes and 42 arcs
\-\-\-\-\-
command completion is disabled
\-\-\-\-\-
wseq > A BANANA </s>
[wseq: A BANANA </s>]
[cate: (NUM_1|NUM_1|A|A) FRUIT_SINGULAR NS_E]
PREDICTED CATEGORIES/WORDS:
                    NS_B (<s> )
                    HAVE (HAVE )
                    WANT (WANT )
                    NS_B (<s> )
                    HAVE (HAVE )
                    WANT (WANT )
.fi
.if n \{\
.RE
.\}
.sp
.SH "SEE ALSO"
.PP

\fB mkdfa.pl \fR( 1 )
,
\fB generate \fR( 1 )
,
\fB accept_check \fR( 1 )
.SH "COPYRIGHT"
.PP
Copyright (c) 1991\-2013 Kawahara Lab\&., Kyoto University
.PP
Copyright (c) 1997\-2000 Information\-technology Promotion Agency, Japan
.PP
Copyright (c) 2000\-2005 Shikano Lab\&., Nara Institute of Science and Technology
.PP
Copyright (c) 2005\-2013 Julius project team, Nagoya Institute of Technology
.SH "LICENSE"
.PP
The same as Julius\&.
