'\" t
.\"     Title: 
    jclient.pl
  
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 19/12/2013
.\"    Manual: 
.\"    Source: 
.\"  Language: Japanese
.\"
.TH "JCLIENT\&.PL" "1" "19/12/2013" ""
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "名前"

    jclient.pl
   \- perl 版サンプルクライアント
.SH "概要"
.HP \w'\fBjclient\&.pl\fR\ 'u
\fBjclient\&.pl\fR
.SH "DESCRIPTION"
.PP
Julius に付属のサンプルクライアント "jcontrol" の Perl 版です． モジュール（サーバ）モードで動く Julius から認識結果を受け取ったり， Julius を制御したりできます．
.PP
わずか 57 行の簡単なプログラムです．アプリケーションへ Julius を組み込 む際の参考になれば幸いです．ご自由にご利用ください。
.SH "EXAMPLES"
.PP .if n \{\ .RS 4 .\} .nf % \fBjulius\fR \-C \&.\&.\&. \-module .fi .if n \{\ .RE .\}
上記のようにして Julius をモジュールモードで起動した後，jclient\&.pl を 起動します．接続するホストのデフォルトは localhost, ポート番号は 10500 です．変えたい場合はスクリプトの冒頭を書き換えてください．
.sp .if n \{\ .RS 4 .\} .nf % \fBjclient\&.pl\fR .fi .if n \{\ .RE .\}
音声入力を行えば，イベント内容や結果が jclient\&.pl 側に送信され， 標準出力に出力されます．また，jclient\&.pl に対してコマンドを入力する （最後に Enter を押す）と，Julius にコマンドが送信され，Julius が制御されます． コマンドは，仕様書にあるモジュールコマンドを生のまま記述します．
.SH "SEE ALSO"
.PP

\fB julius \fR( 1 )
,
\fB jcontrol \fR( 1 )
.SH "COPYRIGHT"
.PP
jclient\&.pl は 西村竜一 さん (nisimura@sys\&.wakayama\-u\&.ac\&.jp) によって作 成されました．本プログラムのご利用に関しては，作者は一切の保証をしませ ん．各自の責任のもとでご利用ください．
.PP
感想、御意見、御要望などのフィードバックは歓迎いたしますので， 上記メールアドレス，または下記ホームページへ御連絡ください．
.PP
http://w3voice\&.jp/
